FROM  mhart/alpine-node:latest

MAINTAINER Scott Molinari <scott.molinari@adduco.de>

ENV PATH /usr/lib/node_modules:$PATH

RUN apk add --no-cache bash &&\
    cd / &&\
    npm install -g quasar-cli &&\
    quasar init /opt/app

WORKDIR /opt/app

RUN npm install

EXPOSE 8080

CMD /bin/sh