FROM  quasarframework/quasar-dev:latest

MAINTAINER Scott Molinari <scott.molinari@adduco.de>

ENV PATH /usr/lib/node_modules:$PATH

RUN apk add --no-cache bash

WORKDIR /opt/app

COPY package.json /opt/app/package.json

RUN npm install

COPY . /opt/app

EXPOSE 8080

CMD /bin/sh