version: '2'

services:
  quasar-dev:
    build: .
    image: quasarframework/quasar-dev
    command: sh
    volumes:
      - .:/opt/app
      - /opt/app/node_modules
    ports:
      - 8080:8080
    tty: true
